apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-java
  name: app-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java
    spec:
      containers:
        - image: quay.io/openshift-pipeline/vote-api:latest
          imagePullPolicy: Always
          name: pipelines-vote-api
          ports:
            - containerPort: 9000
              protocol: TCP
