apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-java
  name: app-java
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: app-java
